### ISSUE TITLE
支付鸭有出新招，条纹宽度变了

### ISSUE THREAD

**Issue by cjahv** [JayFang1993/AlipayAR#1]
有破解的打算吗？

**Comment by abuccts** [comment]
You can try [ar-lucky-money-hunt](https://github.com/abuccts/ar-lucky-money-hunt).

**Comment by JayFang1993** [comment]
不打算破解，也没有思路，要做好肯定需要用到机器学习的知识，本来就是为了玩玩~
你可以参考 @abuccts 提供的方案
